/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'quickstart',
    {
      type: 'category',
      label: 'Installation',
      link: {
        type: 'doc',
        id: 'installation',
      },
      items: [
        'installation/cdn',
        {
          type: 'category',
          label: 'Documentation sites',
          items: [
            'installation/docusaurus',
            'installation/sphinx',
            'installation/mkdocs',
            'installation/nextra',
            'installation/fumadocs',
            'installation/starlight',
            'installation/vitepress',
            'installation/vuepress',
            'installation/antora',
            'installation/gitbook',
            'installation/mintlify',
            {
              type: 'doc',
              id: 'installation/readme',
              label: 'ReadMe',
            },
            'installation/readthedocs',
            'installation/paligo',
            'installation/madcap-flare',
          ],
        },
        {
          type: 'category',
          label: 'JavaScript & React apps',
          items: [
            'installation/npm',
            'installation/react',
            'installation/vue',
            'installation/nextjs',
            'installation/astro',
            'installation/gatsby',
            'installation/hugo',
            'installation/jekyll',
          ],
        },
        {
          type: 'category',
          label: 'Website builders',
          items: [
            'installation/wordpress',
            'installation/webflow',
            'installation/confluence',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Customization',
      link: {
        type: 'doc',
        id: 'customization',
      },
      items: [
        {
          type: 'category',
          label: 'User interface',
          items: [
            'customization/layout',
            'customization/styles',
            'customization/dark-mode',
            'customization/embedded-mode',
          ],
        },
        {
          type: 'category',
          label: 'Behaviour',
          items: [
            'customization/initial-message',
            'customization/suggested-questions',
            'customization/models',
            'customization/custom-prompt',
            'customization/reasoning-modes',
            'customization/data-privacy',
            'customization/search',
            'customization/search-filters',
            'customization/workflows',
            ],
        },
        {
          type: 'category',
          label: 'Sources',
          link: {
            type: 'doc',
            id: 'customization/data-sources/overview'
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'customization/data-sources',
            }
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'Administration',
      link: {
        type: 'doc',
        id: 'administration',
      },
      items: [
        'administration/team',
        'administration/roles',
        'administration/projects',
        'administration/analytics',
        'administration/subscription',
        'administration/whitelabel',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      link: {
        type: 'doc',
        id: 'integrations',
      },
      items: [
        'integrations/mcp-server',
        'integrations/github-workflow',
        'integrations/custom-gpt',
        'integrations/zapier',
        'integrations/make',
        'integrations/n8n',
        {
          type: 'category',
          label: 'REST API',
          link: {
            type: 'doc',
            id: 'api/biel-ai-rest-api-beta',
          },
          items: require('./docs/api/sidebar'),
        },
      ],
    },

    {
      type: 'category',
      label: 'Security',
      link: {
        type: 'doc',
        id: 'security',
      },
      items: [
        'security/overview',
        'security/checklist',
        'security/providers',
      ],
    },
    'support',
    'release-notes',
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
