/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'quickstart',
    {
      type: 'category',
      label: 'Installation',
      link: {
        type: 'generated-index',
        description: 'Step-by-step installation guides for a range of programming languages and frameworks.'
      },
      items: [
        'installation/cdn',
        {
          type: 'category',
          label: 'Documentation sites',
          items: [
            'installation/docusaurus',
            'installation/sphinx',
            'installation/mkdocs',
            'installation/nextra',
            'installation/fumadocs',
            'installation/starlight',
            'installation/vitepress',
            'installation/vuepress',
            'installation/antora',
            'installation/gitbook',
            'installation/mintlify',
            'installation/readme',
            'installation/readthedocs',
            'installation/paligo',
            'installation/madcap-flare',
          ],
        },
        {
          type: 'category',
          label: 'JavaScript & React apps',
          items: [
            'installation/npm',
            'installation/react',
            'installation/vue',
            'installation/nextjs',
            'installation/astro',
            'installation/gatsby',
            'installation/hugo',
            'installation/jekyll',
          ],
        },
        {
          type: 'category',
          label: 'Website builders',
          items: [
            'installation/wordpress',
            'installation/webflow',
            'installation/confluence',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Customization',
      link: {
        type: 'doc',
        id: 'customization',
      },
      items: [
        {
          type: 'category',
          label: 'User interface',
          items: [
            'customization/layout',
            'customization/styles',
            'customization/dark-mode',
            'customization/embedded-mode',
          ],
        },
        {
          type: 'category',
          label: 'Behaviour',
          items: [
            'customization/initial-message',
            'customization/suggested-questions',
            'customization/think-mode',
            'customization/search',
            'customization/data-privacy',
          ],
        },
        {
          type: 'category',
          label: 'Sources',
          link: {
            type: 'doc',
            id: 'customization/data-sources/overview'
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'customization/data-sources',
            }
          ],
        },
        {
          type: 'category',
          label: 'AI configuration',
          items: [
            'customization/models',
            'customization/custom-prompt',
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'Administration',
      link: {
        type: 'generated-index',
        description: 'Administrative guides and best practices for managing Biel AI.'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'administration',
        }
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      link: {
        type: 'generated-index',
        description: 'Connect Biel.ai to AI development tools, IDEs, and other platforms to give them access to your documentation.'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'integrations',
        },
        {
          type: 'category',
          label: 'REST API',
          link: {
            type: 'doc',
            id: 'api/biel-ai-rest-api-beta',
          },
          items: require('./docs/api/sidebar'),
        },
      ],
    },

    {
      type: 'category',
      label: 'Security',
      link: {
        type: 'generated-index',
        description: 'Security best practices and guidelines for Biel AI.'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'security',
        }
      ],
    },
    'support',
    'release-notes',
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
