/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'quickstart',
    {
      type: 'category',
      label: 'Installation',
      link: {
        type: 'generated-index',
        description: 'Step-by-step installation guides for a range of programming languages and frameworks.'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'installation',
        }
      ],
    },
    {
      type: 'category',
      label: 'Customization',
      items: [
        {
          type: 'autogenerated',
          dirName: 'customization',
        }
      ],
    },
    {
      type: 'category',
      label: 'Administration',
      items: [
        {
          type: 'autogenerated',
          dirName: 'administration',
        }
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        {
          type: 'autogenerated',
          dirName: 'security',
        }
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'doc',
        id: 'api/biel-ai-rest-api',
      },
      items: require('./docs/api/sidebar'),
    },
    'support',
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
